---
title: "Project 0 Report"
author: |
    | Analyst: Max McGrath
    | Investigator: Nichole Carlson
    | Report generated: `r format(Sys.Date(), '%m/%d/%Y')`
header-includes:
    - \usepackage{setspace}\doublespacing
    - \usepackage{titling}
    - \preauthor{\begin{flushleft}}
    - \postauthor{\end{flushleft}}  
output: pdf_document
indent: true
mainfont: Times New Roman
fontsize: 12pt
geometry: margin=1in
---
<!-- Citation: Header flags from William Lippitt -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("..")
source("Code/1-DataPrep.R")
source("Code/2-EDA.R")
source("Code/3-Analysis-Aim1.R")
source("Code/4-Analysis-Aim2.R")
source("Code/5-Analysis-Aim3.R")
```

## Introduction

This analysis evaluates the efficacy of a novel, take-home collection device
used to measure salivary cortisol and DHEA levels throughout the day, and
examines DHEA and cortisol level time trends. The
device was provided to 31 healthy control subjects who were asked to collect
saliva samples immediately upon waking, 30 minutes after waking, before lunch,
and 600 minutes after waking. The time of waking and the time before lunch were
left to the discretion of each subject. Each subject was asked to collect 
four samples per day for three days, providing a maximum of 12 samples per
subject. 

The samples were collected using a filter
paper device termed the Saliva Procurement and Integrated Testing (SPIT)
booklet which was kept in a bottle with an electronic monitoring cap (MEM). 
Subjects
were asked to manually record the time the sample was taken, and the electronic
monitoring cap also recorded the timing of the sample. From each sample,
cortisol and DHEA levels were measured in nanomoles per liter. 

This analysis has three aims: (1) evaluate agreement between the subject's
recordings of sampling times and those recorded by the MEM, (2) evaluate subject
adherence to specified sample timing, and (3) quantify
changes of cortisol and DHEA over time.

As such, we will test three hypotheses: (1) Subject's booklet recordings and the
times recorded by the MEM are significantly correlated, (2) ..., and (3) DHEA
and cortisol levels are positively correlated with time until 30 minutes after
waking and then negatively correlated with time for the remainder of the day.

## Methods

### Data Preperation

### Analysis

To evaluate agreement between the subjects' booklet recordings of sampling 
times and those recorded by the MEM, a linear model was fit with MEM time as the
response variable and booklet time as the predictor. Raw times were used for 
this section, as minutes since waking (which is used for the other sections
of this analysis), yielded a fit with obviously correlated residuals. The
slope estimate of this model was then examined to quantify correlation between
the examined times, and a t-test was conducted to evaluate the estimates
statistical significance. The mean difference between times recorded by MEM and
those recorded in the booklets was also calculated. A plot comparing booklet 
times and MEM times is also provided.

Aim 2: ...

Knowing the data consists of repeated observations from each subject, it is 
foreseeable that intrasubject DHEA and cortisol levels are correlated. So,
to quantify changes in DHEA and cortisol over time, two linear mixed-effects 
models (one for each hormone) were fit with intercepts allowed to vary by 
subject, thereby accounting for this correlation. Further, given
the known diurnal trend in which DHEA and cortisol levels peak 30 minutes after 
waking and then taper throughout the day,
the fixed effects of the linear models were segmented into piecewise
components wherein the linear trends were allowed to differ before and after
30 minutes after waking. For each model, time after waking was used as the sole
predictor, and the natural log of the measurement of DHEA and cortisol levels 
were used as responses for each hormone's respective model.

## Results

The linear model used to test the hypothesis that subject's booklet recordings 
and the times recorded by the MEM are significantly correlated had an estimated 
slope coefficient of 0.9938 with a p-value less than .001. A plot of the MEM
recorded times versus the subject recorded times is included in the appendix
in Figure ???. On average, the MEM recorded times are 7.71 minutes later than
those recorded in the book. A plot of the difference between MEM and booklet
records is provided in Figure ???.

Of the 93 observations for 30 minutes after waking, 33 MEM records and 6 booklet
records were missing. Of those that were not missing, 75.0% of MEM records and
79.3% of booklet records were within 7.5 minutes of subjects' wake-time records.
Further, 86.7% of MEM records and 95% of booklet records are within 15 minutes 
of the 30 minute protocol. On average, MEM records were 11.3 minutes after the
30 minute protocol, and booklet records were 3.49 minutes after the 30 minute 
protocol.

Of the 93 observations for the 600 minute protocol, 21 MEM records and 16
booklet records were missing. Of those that were not missing, 29.2% of MEM 
records and
42.9% of booklet records were within 7.5 minutes of subjects' wake-time records.
45.8% of MEM records and 53.2% of booklet records were within 15 minutes of the
600 minute protocol. On average, MEM records and book records differed from the
600 minute protocol by 54.1 and 42.1 minutes respectively. A box-plot for 
protocol adherence by record type is provided in Figure ???.

Given greater number of complete observations and the superior 
protocol-adherence of booklet records, booklet records were used for the models 
analyzing DHEA and cortisol. Specifically, booklet
recorded minutes after waking were used as the predictor. Records with missing 
booklet times were discarded. Additionally, to meet error assumptions for linear
models, the natural log of DHEA and cortisol levels in nanomoles per Liter
were used as the responses for their respective models. 

For the DHEA model, random intercept estimates for the subjects ranged from 
-0.019 to 0.107 with a standard deviation of 0.530.
The piecewise regression model used to analyze DHEA involves
the estimation of two regression coefficients. The first estimates the slope
of the data prior to the break at 30 minutes, and it was estimated to be 
-0.193 with a 95% confidence interval of (-0.026, -0.128). The second
coefficient estimates the change in slope following the break and was estimated
to be 0.018 with a 95% confidence interval of (0.011, 0.0244). 

For the cortisol model, random intercept estimates for the subjects ranged from
-0.019 to 0.107 with a standard deviation of 0.336. The estimate of the slope
coefficient prior to 30 minutes after waking was 0.003829 with a 95% confidence
interval of (-0.004, 0.011), and the estimate of the change in slope from
before to after 30 minutes was -0.005913 with a 95% confidence interval of
(-0.014, 0.001). Plots of both models for all estimated intercepts are provided
in Figures ??? and ???.

## Conclusions

### Limitations and Further Analysis

## Reproducible research information

The code used to generate this analysis is available on GitHub 
at https://github.com/BIOS6624-UCD/bios6624-MaxMcGrath/tree/main/Project0
. The `Background` folder contains information pertinent to understanding the
analysis but unnecessary for reproducing it. The `Code` folder contains five
files: `1-DataPrep.R`, `2-EDA.R`, `3-Analysis-Aim1.R`, `4-Analysis-Aim2.R`, and
`5-Analysis-Aim3.R`. These R scripts are dependent upon a data file 
`Data/Project0_Clean_v2.csv` which is not available on GitHub, but may be 
requested
by emailing `max.mcgrath@ucdenver.edu`. To run the complete analysis, each
script should be run in the order of the number preceding its filename. The
last directory, `Report`, contains the RMarkdown file `report.Rmd` which may
be used to generate this report (note that it also depends on the aforementioned
data).

This analysis was performed using R version 4.0.4. The following non-base R 
packages were used: lme4 (1.1.26), dplyr (1.0.5), ggplot2 (3.3.3),
stringr (1.4.0), hms (1.0.0), car (3.0-10), and tidyverse (1.3.0).

## Appendix
